
import java.awt.Color;
import java.util.*;
/**
 *
 * @author jom84
 */
public class MovingBlockOverlayUI extends javax.swing.JFrame {
    ArrayList<TrainModel> trains = new ArrayList();
    //ArrayList<Operator> operators = new ArrayList();
    ArrayList<Double> safe_speeds;
    ArrayList<Double> safe_auths;
    double speed = 0;
    double location = 0;
    double bspeed = 0;
    double bauth = 5000;
    double deceleration = -25;
    int mode = 1;
    ArrayList<ScheduleNode> schedule = new ArrayList();
    /**
     * Creates new form MovingBlockOverlayUI
     */
    public MovingBlockOverlayUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        ControlMode = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        PassengerPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ShadyText = new javax.swing.JTextField();
        HerronText = new javax.swing.JTextField();
        SwissText = new javax.swing.JTextField();
        PennText = new javax.swing.JTextField();
        SteelText = new javax.swing.JTextField();
        FirstText = new javax.swing.JTextField();
        StationText = new javax.swing.JTextField();
        SouthText = new javax.swing.JTextField();
        TotalText = new javax.swing.JTextField();
        TrainList = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        InfoPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        TrainSpeedField = new javax.swing.JTextField();
        TrainLocationField = new javax.swing.JTextField();
        BlockSpeedField = new javax.swing.JTextField();
        BlockAuthorityField = new javax.swing.JTextField();
        SpeedVarianceField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        AuthVarianceField = new javax.swing.JTextField();
        ControlPanel = new javax.swing.JPanel();
        MovingBlockDisplay = new javax.swing.JTextField();
        FixedBlockDisplay = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        ShadyScheduleBox = new javax.swing.JTextField();
        HerronScheduleBox = new javax.swing.JTextField();
        SwissScheduleBox = new javax.swing.JTextField();
        PennScheduleBox = new javax.swing.JTextField();
        SteelScheduleBox = new javax.swing.JTextField();
        FirstScheduleBox = new javax.swing.JTextField();
        StationScheduleBox = new javax.swing.JTextField();
        SouthScheduleBox = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        StartScheduleBox = new javax.swing.JTextField();
        NewScheduleButton = new javax.swing.JButton();
        ViewScheduleButton = new javax.swing.JButton();
        AddScheduleButton = new javax.swing.JButton();
        StartButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        MovingBlockRadio = new javax.swing.JRadioButton();
        FixedBlockRadio = new javax.swing.JRadioButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PassengerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Passenger Movement", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 255))); // NOI18N

        jLabel2.setText("Shadyside");

        jLabel3.setText("Herron Ave");

        jLabel4.setText("Swissville");

        jLabel5.setText("Penn Station");

        jLabel6.setText("Steel Plaza");

        jLabel7.setText("First Avenue");

        jLabel8.setText("Station Square");

        jLabel9.setText("South Hills Junction");

        jLabel10.setText("Passengers Currently Onboard:");

        ShadyText.setEditable(false);
        ShadyText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ShadyText.setText("On: 0\tOff: 0");
        ShadyText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShadyTextActionPerformed(evt);
            }
        });

        HerronText.setEditable(false);
        HerronText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        HerronText.setText("On: 0\tOff: 0");
        HerronText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HerronTextActionPerformed(evt);
            }
        });

        SwissText.setEditable(false);
        SwissText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SwissText.setText("On: 0\tOff: 0");
        SwissText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SwissTextActionPerformed(evt);
            }
        });

        PennText.setEditable(false);
        PennText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PennText.setText("On: 0\tOff: 0");
        PennText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PennTextActionPerformed(evt);
            }
        });

        SteelText.setEditable(false);
        SteelText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SteelText.setText("On: 0\tOff: 0");
        SteelText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SteelTextActionPerformed(evt);
            }
        });

        FirstText.setEditable(false);
        FirstText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FirstText.setText("On: 0\tOff: 0");
        FirstText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstTextActionPerformed(evt);
            }
        });

        StationText.setEditable(false);
        StationText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        StationText.setText("On: 0\tOff: 0");
        StationText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StationTextActionPerformed(evt);
            }
        });

        SouthText.setEditable(false);
        SouthText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SouthText.setText("On: 0\tOff: 0");
        SouthText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SouthTextActionPerformed(evt);
            }
        });

        TotalText.setEditable(false);
        TotalText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TotalText.setText("0");
        TotalText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PassengerPanelLayout = new javax.swing.GroupLayout(PassengerPanel);
        PassengerPanel.setLayout(PassengerPanelLayout);
        PassengerPanelLayout.setHorizontalGroup(
            PassengerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PassengerPanelLayout.createSequentialGroup()
                .addGroup(PassengerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PassengerPanelLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel7))
                    .addGroup(PassengerPanelLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel8))
                    .addGroup(PassengerPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel9))
                    .addGroup(PassengerPanelLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel4))
                    .addGroup(PassengerPanelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel2))
                    .addGroup(PassengerPanelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel3))
                    .addGroup(PassengerPanelLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel5))
                    .addGroup(PassengerPanelLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel6))
                    .addGroup(PassengerPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PassengerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addGroup(PassengerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(HerronText, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ShadyText, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SwissText, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PennText, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SteelText, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(FirstText, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(StationText, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SouthText, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PassengerPanelLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(TotalText, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        PassengerPanelLayout.setVerticalGroup(
            PassengerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PassengerPanelLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ShadyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HerronText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SwissText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PennText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SteelText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FirstText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StationText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SouthText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TotalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TrainList.setMaximumRowCount(32);
 /*       TrainList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrainListActionPerformed(evt);
            }
        }); */

        jLabel1.setText("Select Train:");

        InfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Train And Block Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 255))); // NOI18N

        jLabel11.setText("Train Speed:");

        jLabel12.setText("Train Location:");

        jLabel13.setText("Block Speed:");

        jLabel14.setText("Block Authority:");

        jLabel15.setText("Speed Variance:");

        TrainSpeedField.setEditable(false);
        TrainSpeedField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrainSpeedFieldActionPerformed(evt);
            }
        });

        TrainLocationField.setEditable(false);

        BlockSpeedField.setEditable(false);
        BlockSpeedField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlockSpeedFieldActionPerformed(evt);
            }
        });

        BlockAuthorityField.setEditable(false);

        SpeedVarianceField.setEditable(false);
        SpeedVarianceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpeedVarianceFieldActionPerformed(evt);
            }
        });

        jLabel24.setText("Auth Variance:");

        AuthVarianceField.setEditable(false);

        javax.swing.GroupLayout InfoPanelLayout = new javax.swing.GroupLayout(InfoPanel);
        InfoPanel.setLayout(InfoPanelLayout);
        InfoPanelLayout.setHorizontalGroup(
            InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel24))
                .addGap(26, 26, 26)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TrainSpeedField)
                    .addComponent(TrainLocationField)
                    .addComponent(BlockSpeedField)
                    .addComponent(BlockAuthorityField)
                    .addComponent(SpeedVarianceField, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(AuthVarianceField))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        InfoPanelLayout.setVerticalGroup(
            InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TrainSpeedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(TrainLocationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(BlockSpeedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(BlockAuthorityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(SpeedVarianceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(AuthVarianceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ControlPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Control Mode", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 255))); // NOI18N

        MovingBlockDisplay.setEditable(false);
        MovingBlockDisplay.setBackground(new java.awt.Color(0, 255, 0));
        MovingBlockDisplay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MovingBlockDisplay.setText("Moving Block");

        FixedBlockDisplay.setBackground(new java.awt.Color(255, 0, 0));
        FixedBlockDisplay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FixedBlockDisplay.setText("Fixed Block");

        javax.swing.GroupLayout ControlPanelLayout = new javax.swing.GroupLayout(ControlPanel);
        ControlPanel.setLayout(ControlPanelLayout);
        ControlPanelLayout.setHorizontalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MovingBlockDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FixedBlockDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addContainerGap())
        );
        ControlPanelLayout.setVerticalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MovingBlockDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FixedBlockDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Train Scheduler", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 255))); // NOI18N

        jLabel19.setText("Shady:");

        jLabel20.setText("Herron:");

        jLabel33.setText("Swiss:");

        jLabel34.setText("Penn:");

        jLabel35.setText("Steel:");

        jLabel36.setText("First:");

        jLabel37.setText("Station:");

        jLabel38.setText("South:");

        HerronScheduleBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HerronScheduleBoxActionPerformed(evt);
            }
        });

        FirstScheduleBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstScheduleBoxActionPerformed(evt);
            }
        });

        jLabel39.setText("Start Time:");

        NewScheduleButton.setText("Make New Schedule");
        NewScheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewScheduleButtonActionPerformed(evt);
            }
        });

        ViewScheduleButton.setText("View Schedule");
        ViewScheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewScheduleButtonActionPerformed(evt);
            }
        });

        AddScheduleButton.setText("Add To Schedule");
        AddScheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddScheduleButtonActionPerformed(evt);
            }
        });

        StartButton.setText("Start");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ViewScheduleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(AddScheduleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(StartButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel35)
                                .addComponent(jLabel34)
                                .addComponent(jLabel33)
                                .addComponent(jLabel20)
                                .addComponent(jLabel19)
                                .addComponent(jLabel36)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel37)
                                        .addGap(24, 24, 24))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(StationScheduleBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                                .addComponent(FirstScheduleBox, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SouthScheduleBox)
                                .addComponent(SteelScheduleBox)
                                .addComponent(PennScheduleBox)
                                .addComponent(SwissScheduleBox)
                                .addComponent(HerronScheduleBox)
                                .addComponent(ShadyScheduleBox)))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel39)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(StartScheduleBox, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)))
                    .addComponent(NewScheduleButton))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(ShadyScheduleBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(HerronScheduleBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(SwissScheduleBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(PennScheduleBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(SteelScheduleBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(FirstScheduleBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(StationScheduleBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(SouthScheduleBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(StartScheduleBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(NewScheduleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewScheduleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddScheduleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StartButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Block Control Mode", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 255))); // NOI18N

        ControlMode.add(MovingBlockRadio);
        MovingBlockRadio.setText("Moving Block");
        MovingBlockRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovingBlockRadioActionPerformed(evt);
            }
        });

        ControlMode.add(FixedBlockRadio);
        FixedBlockRadio.setSelected(true);
        FixedBlockRadio.setText("Fixed Block");
        FixedBlockRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FixedBlockRadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MovingBlockRadio)
                    .addComponent(FixedBlockRadio))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MovingBlockRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FixedBlockRadio)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PassengerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ControlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TrainList, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TrainList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PassengerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(InfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ControlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(89, 89, 89))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShadyTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShadyTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ShadyTextActionPerformed

    private void HerronTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HerronTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HerronTextActionPerformed

    private void SwissTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SwissTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SwissTextActionPerformed

    private void PennTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PennTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PennTextActionPerformed

    private void SteelTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SteelTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SteelTextActionPerformed

    private void FirstTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstTextActionPerformed

    private void StationTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StationTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StationTextActionPerformed

    private void SouthTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SouthTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SouthTextActionPerformed

    private void TotalTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalTextActionPerformed

    private void TrainSpeedFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrainSpeedFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TrainSpeedFieldActionPerformed

    private void SpeedVarianceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpeedVarianceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SpeedVarianceFieldActionPerformed

   /* private void TrainListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrainListActionPerformed
        String new_label = (String)TrainList.getSelectedItem();
        TrainList.setSelectedItem(new_label);
        
        int index = Integer.parseInt(new_label)-1;
        MBOTrain train_to_show = trains.get(index);
        //curr_train = train_to_show;
        
        updateDisplay();
    }//GEN-LAST:event_TrainListActionPerformed*/

    private void MovingBlockRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovingBlockRadioActionPerformed
        MovingBlockDisplay.setBackground(Color.GREEN);
        FixedBlockDisplay.setBackground(Color.RED);
        mode = 1;
        updateDisplay();
    }//GEN-LAST:event_MovingBlockRadioActionPerformed

    private void FixedBlockRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FixedBlockRadioActionPerformed
        FixedBlockDisplay.setBackground(Color.GREEN);
        MovingBlockDisplay.setBackground(Color.RED);
        mode = 0;
        updateDisplay();
    }//GEN-LAST:event_FixedBlockRadioActionPerformed

    private void HerronScheduleBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HerronScheduleBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HerronScheduleBoxActionPerformed

    private void NewScheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewScheduleButtonActionPerformed
        schedule = new ArrayList();
        double start_time = Double.parseDouble(StartScheduleBox.getText());
        double time_Shady = Double.parseDouble(ShadyScheduleBox.getText());
        double time_to_add = start_time + time_Shady;
        ScheduleNode node_to_add = new ScheduleNode("Shady",time_to_add);
        schedule.add(node_to_add);
        double time_Herron = Double.parseDouble(HerronScheduleBox.getText());
        time_to_add += time_Herron;
        node_to_add = new ScheduleNode("Herron",time_to_add);
        schedule.add(node_to_add);
        double time_Swiss = Double.parseDouble(SwissScheduleBox.getText());
        time_to_add += time_Swiss;
        node_to_add = new ScheduleNode("Swiss",time_to_add);
        schedule.add(node_to_add);
        double time_Penn = Double.parseDouble(PennScheduleBox.getText());
        time_to_add += time_Penn;
        node_to_add = new ScheduleNode("Penn",time_to_add);
        schedule.add(node_to_add);
        double time_Steel = Double.parseDouble(SteelScheduleBox.getText());
        time_to_add += time_Steel;
        node_to_add = new ScheduleNode("Steel",time_to_add);
        schedule.add(node_to_add);
        double time_First = Double.parseDouble(FirstScheduleBox.getText());
        time_to_add += time_First;
        node_to_add = new ScheduleNode("First",time_to_add);
        schedule.add(node_to_add);
        double time_Station = Double.parseDouble(StationScheduleBox.getText());
        time_to_add += time_Station;
        node_to_add = new ScheduleNode("Station",time_to_add);
        schedule.add(node_to_add);
        double time_South = Double.parseDouble(SouthScheduleBox.getText());
        time_to_add += time_South;
        node_to_add = new ScheduleNode("South",time_to_add);
        schedule.add(node_to_add);
    }//GEN-LAST:event_NewScheduleButtonActionPerformed

    private void ViewScheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewScheduleButtonActionPerformed
        System.out.println(schedule);
    }//GEN-LAST:event_ViewScheduleButtonActionPerformed

    private void AddScheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddScheduleButtonActionPerformed
        double start_time = Double.parseDouble(StartScheduleBox.getText());
        double time_Shady = Double.parseDouble(ShadyScheduleBox.getText());
        double time_to_add = start_time + time_Shady;
        ScheduleNode node_to_change = schedule.get(0);
        node_to_change.addTime(time_to_add);
        double time_Herron = Double.parseDouble(HerronScheduleBox.getText());
        time_to_add += time_Herron;
        node_to_change = schedule.get(1);
        node_to_change.addTime(time_to_add);
        double time_Swiss = Double.parseDouble(SwissScheduleBox.getText());
        time_to_add += time_Swiss;
        node_to_change = schedule.get(2);
        node_to_change.addTime(time_to_add);
        double time_Penn = Double.parseDouble(PennScheduleBox.getText());
        time_to_add += time_Penn;
        node_to_change = schedule.get(3);
        node_to_change.addTime(time_to_add);
        double time_Steel = Double.parseDouble(SteelScheduleBox.getText());
        time_to_add += time_Steel;
        node_to_change = schedule.get(4);
        node_to_change.addTime(time_to_add);
        double time_First = Double.parseDouble(FirstScheduleBox.getText());
        time_to_add += time_First;
        node_to_change = schedule.get(5);
        node_to_change.addTime(time_to_add);
        double time_Station = Double.parseDouble(StationScheduleBox.getText());
        time_to_add += time_Station;
        node_to_change = schedule.get(6);
        node_to_change.addTime(time_to_add);
        double time_South = Double.parseDouble(SouthScheduleBox.getText());
        time_to_add += time_South;
        node_to_change = schedule.get(7);
        node_to_change.addTime(time_to_add);
    }

    private void FirstScheduleBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstScheduleBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstScheduleBoxActionPerformed

    private void BlockSpeedFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlockSpeedFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BlockSpeedFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovingBlockOverlayUI().setVisible(true);
            }
        });
    }
    
    public void updateDisplay(){
                
        /*Hashtable stops = curr_train.getStops();
        int[] vals = new int[2];
        vals = (int[])stops.get("Shady");
        ShadyText.setText("On: " + vals[0] + "\tOff: " + vals[1]);
        vals = (int[])stops.get("Herron");
        HerronText.setText("On: " + vals[0] + "\tOff: " + vals[1]);
        vals = (int[])stops.get("Swiss");
        SwissText.setText("On: " + vals[0] + "\tOff: " + vals[1]);
        vals = (int[])stops.get("Penn");
        PennText.setText("On: " + vals[0] + "\tOff: " + vals[1]);
        vals = (int[])stops.get("Steel");
        SteelText.setText("On: " + vals[0] + "\tOff: " + vals[1]);
        vals = (int[])stops.get("First");
        FirstText.setText("On: " + vals[0] + "\tOff: " + vals[1]);
        vals = (int[])stops.get("Station");
        StationText.setText("On: " + vals[0] + "\tOff: " + vals[1]);
        vals = (int[])stops.get("South");
        SouthText.setText("On: " + vals[0] + "\tOff: " + vals[1]);
        TotalText.setText(curr_train.getTotal());
        
        TrainSpeedField.setText(curr_train.getSpeed());
        TrainLocationField.setText(curr_train.getLoc());
        
        if(mode == 0){
            BlockSpeedField.setText(String.valueOf(safe_speed));
            BlockAuthorityField.setText(String.valueOf(safe_authority));
            double speed_variance = Double.parseDouble(curr_train.getSpeed()) - safe_speed;
            SpeedVarianceField.setText(String.valueOf(speed_variance));
            double auth_variance = Double.parseDouble(curr_train.getLoc()) - safe_authority;
            AuthVarianceField.setText(String.valueOf(auth_variance));
        }
        if(mode == 1){
            safe_speed = calculateSafeSpeed(curr_train);
            safe_authority = calculateSafeAuthority(curr_train);
            BlockSpeedField.setText(String.valueOf(safe_speed));
            BlockAuthorityField.setText(String.valueOf(safe_authority));
            double speed_variance = Double.parseDouble(curr_train.getSpeed()) - safe_speed;
            SpeedVarianceField.setText(String.valueOf(speed_variance));
            double auth_variance = Double.parseDouble(curr_train.getLoc()) - safe_authority;
            AuthVarianceField.setText(String.valueOf(auth_variance));
        }
        
        curr_train.setSafes(safe_speed,safe_authority);*/
        TrainSpeedField.setText(String.valueOf(speed));
        TrainLocationField.setText(String.valueOf(location));
        BlockSpeedField.setText(String.valueOf(bspeed));
        BlockAuthorityField.setText(String.valueOf(bauth));
        double speed_var = bspeed - speed;
        SpeedVarianceField.setText(String.valueOf(speed_var));
        double auth_var = bauth - location;
        AuthVarianceField.setText(String.valueOf(auth_var));
    }
    
    public void updateSpeed(double s){
        speed = s;
        updateDisplay();
    }
    
    public void updatePosition(double p){
        location = Math.abs(p);
        updateDisplay();
    }
    
    public void updateBlockSpeed(double s){
        bspeed = s;
        updateDisplay();
    }
    
    public void updateBlockAuthority(double a){
        bauth = a;
        updateDisplay();
    }
    
    public double getbauth(){
        return bauth;
    }
    
    public double getbspeed(){
        return bspeed;
    }
 /*   public double calculateSafeAuthority(MBOTrain curr_train){
        double loc1 = Double.parseDouble(curr_train.getLoc());
        double speed1 = Double.parseDouble(curr_train.getSpeed());
        double loc2 = Double.MAX_VALUE;
        double speed2 = 0;
        for(MBOTrain t : trains){
            if(Double.parseDouble(t.getLoc()) < loc2){
                loc2 = Double.parseDouble(t.getLoc());
                speed2 = Double.parseDouble(t.getSpeed());
            }
        }
        double v_final = 0;
        double t_final = (0 - speed1)/deceleration;
        double distance = speed1 * t_final + .5 * deceleration * Math.pow(t_final, 2);
        return loc2 - (distance + loc1);
    }*/
    
   /* public double calculateSafeSpeed(MBOTrain curr_train){
        double loc1 = Double.parseDouble(curr_train.getLoc());
        double speed1 = Double.parseDouble(curr_train.getSpeed());
        double loc2 = Double.MAX_VALUE;
        double speed2 = 0;
        for(MBOTrain t : trains){
            if(Double.parseDouble(t.getLoc()) < loc2){
                loc2 = Double.parseDouble(t.getLoc());
                speed2 = Double.parseDouble(t.getSpeed());
            }
        }
        return speed2;
    }*/

    public ArrayList getSchedule(){
        return schedule;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton AddScheduleButton;
    public javax.swing.JTextField AuthVarianceField;
    public javax.swing.JTextField BlockAuthorityField;
    public javax.swing.JTextField BlockSpeedField;
    private javax.swing.ButtonGroup ControlMode;
    public javax.swing.JPanel ControlPanel;
    public javax.swing.JTextField FirstScheduleBox;
    public javax.swing.JTextField FirstText;
    public javax.swing.JTextField FixedBlockDisplay;
    public javax.swing.JRadioButton FixedBlockRadio;
    public javax.swing.JTextField HerronScheduleBox;
    public javax.swing.JTextField HerronText;
    public javax.swing.JPanel InfoPanel;
    public javax.swing.JTextField MovingBlockDisplay;
    public javax.swing.JRadioButton MovingBlockRadio;
    public javax.swing.JButton NewScheduleButton;
    public javax.swing.JPanel PassengerPanel;
    public javax.swing.JTextField PennScheduleBox;
    public javax.swing.JTextField PennText;
    public javax.swing.JTextField ShadyScheduleBox;
    public javax.swing.JTextField ShadyText;
    public javax.swing.JTextField SouthScheduleBox;
    public javax.swing.JTextField SouthText;
    public javax.swing.JTextField SpeedVarianceField;
    public javax.swing.JButton StartButton;
    public javax.swing.JTextField StartScheduleBox;
    public javax.swing.JTextField StationScheduleBox;
    public javax.swing.JTextField StationText;
    public javax.swing.JTextField SteelScheduleBox;
    public javax.swing.JTextField SteelText;
    public javax.swing.JTextField SwissScheduleBox;
    public javax.swing.JTextField SwissText;
    public javax.swing.JTextField TotalText;
    public javax.swing.JComboBox TrainList;
    public javax.swing.JTextField TrainLocationField;
    public javax.swing.JTextField TrainSpeedField;
    public javax.swing.JButton ViewScheduleButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFrame jFrame1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    public javax.swing.JLabel jLabel24;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel33;
    public javax.swing.JLabel jLabel34;
    public javax.swing.JLabel jLabel35;
    public javax.swing.JLabel jLabel36;
    public javax.swing.JLabel jLabel37;
    public javax.swing.JLabel jLabel38;
    public javax.swing.JLabel jLabel39;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
