
import java.awt.Color;
import java.util.*;
/**
 *
 * @author jom84
 */
public class MovingBlockOverlayUI extends javax.swing.JFrame {
    TrainModel curr_train;
    Vector<TrainModel> trains = new Vector();
    ArrayList<Double> safe_speeds;
    ArrayList<Double> safe_auths;
    double speed = 0;
    double location = 0;
    double bspeed = 0;
    double bauth = 5000;
    double deceleration = -25;
    int mode = 1;
    ArrayList<ScheduleNode> schedule = new ArrayList();
    /**
     * Creates new form MovingBlockOverlayUI
     */
    public MovingBlockOverlayUI() {
        initComponents();
    }
    
    public double getbauth(){
        return bauth;
    }
    
    public double getbspeed(){
        return bspeed;
    }
    
    public void updateSpeed(double s){
        speed = s;
        updateDisplay();
    }
    
    public void updatePosition(double p){
        location = p;
        updateDisplay();
    }
    
    public void updateBlockSpeed(double s){
        bspeed = s;
        updateDisplay();
    }
    
    public void updateBlockAuthority(double a){
        bauth = a;
        updateDisplay();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        ControlMode = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        PassengerPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        TotalText = new javax.swing.JTextField();
        TrainList = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        InfoPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        TrainSpeedField = new javax.swing.JTextField();
        TrainLocationField = new javax.swing.JTextField();
        BlockSpeedField = new javax.swing.JTextField();
        BlockAuthorityField = new javax.swing.JTextField();
        SpeedVarianceField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        AuthVarianceField = new javax.swing.JTextField();
        ControlPanel = new javax.swing.JPanel();
        MovingBlockDisplay = new javax.swing.JTextField();
        FixedBlockDisplay = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        sLabel9 = new javax.swing.JLabel();
        sLabel10 = new javax.swing.JLabel();
        sLabel11 = new javax.swing.JLabel();
        sLabel12 = new javax.swing.JLabel();
        sLabel13 = new javax.swing.JLabel();
        sLabel14 = new javax.swing.JLabel();
        sLabel15 = new javax.swing.JLabel();
        sLabel16 = new javax.swing.JLabel();
        sBox1 = new javax.swing.JTextField();
        sBox2 = new javax.swing.JTextField();
        sBox3 = new javax.swing.JTextField();
        sBox4 = new javax.swing.JTextField();
        sBox5 = new javax.swing.JTextField();
        sBox6 = new javax.swing.JTextField();
        sBox7 = new javax.swing.JTextField();
        sBox8 = new javax.swing.JTextField();
        sLabel17 = new javax.swing.JLabel();
        NewScheduleButton = new javax.swing.JButton();
        ViewScheduleButton = new javax.swing.JButton();
        AddScheduleButton = new javax.swing.JButton();
        StartButton = new javax.swing.JButton();
        LineSelectBox = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        sLabel8 = new javax.swing.JLabel();
        sLabel7 = new javax.swing.JLabel();
        sLabel6 = new javax.swing.JLabel();
        sLabel5 = new javax.swing.JLabel();
        sLabel4 = new javax.swing.JLabel();
        sLabel3 = new javax.swing.JLabel();
        sLabel2 = new javax.swing.JLabel();
        sLabel1 = new javax.swing.JLabel();
        sLabel18 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        StartTimeBox = new javax.swing.JTextField();
        sBox9 = new javax.swing.JTextField();
        sBox10 = new javax.swing.JTextField();
        sBox11 = new javax.swing.JTextField();
        sBox12 = new javax.swing.JTextField();
        sBox13 = new javax.swing.JTextField();
        sBox14 = new javax.swing.JTextField();
        sBox15 = new javax.swing.JTextField();
        sBox16 = new javax.swing.JTextField();
        sBox17 = new javax.swing.JTextField();
        sBox18 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        MovingBlockRadio = new javax.swing.JRadioButton();
        FixedBlockRadio = new javax.swing.JRadioButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PassengerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Passenger Movement", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 255))); // NOI18N

        jLabel10.setText("Passengers Currently Onboard:");

        TotalText.setEditable(false);
        TotalText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TotalText.setText("0");
        TotalText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PassengerPanelLayout = new javax.swing.GroupLayout(PassengerPanel);
        PassengerPanel.setLayout(PassengerPanelLayout);
        PassengerPanelLayout.setHorizontalGroup(
            PassengerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PassengerPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PassengerPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(TotalText, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PassengerPanelLayout.setVerticalGroup(
            PassengerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PassengerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TotalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        TrainList.setMaximumRowCount(32);
        TrainList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrainListActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Train:");

        InfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Train And Block Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 255))); // NOI18N

        jLabel11.setText("Train Speed:");

        jLabel12.setText("Train Location:");

        jLabel13.setText("Block Speed:");

        jLabel14.setText("Block Authority:");

        jLabel15.setText("Speed Variance:");

        TrainSpeedField.setEditable(false);
        TrainSpeedField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrainSpeedFieldActionPerformed(evt);
            }
        });

        TrainLocationField.setEditable(false);

        BlockSpeedField.setEditable(false);
        BlockSpeedField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlockSpeedFieldActionPerformed(evt);
            }
        });

        BlockAuthorityField.setEditable(false);

        SpeedVarianceField.setEditable(false);
        SpeedVarianceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpeedVarianceFieldActionPerformed(evt);
            }
        });

        jLabel24.setText("Auth Variance:");

        AuthVarianceField.setEditable(false);

        javax.swing.GroupLayout InfoPanelLayout = new javax.swing.GroupLayout(InfoPanel);
        InfoPanel.setLayout(InfoPanelLayout);
        InfoPanelLayout.setHorizontalGroup(
            InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel24))
                .addGap(26, 26, 26)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TrainSpeedField)
                    .addComponent(TrainLocationField)
                    .addComponent(BlockSpeedField)
                    .addComponent(BlockAuthorityField)
                    .addComponent(SpeedVarianceField, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(AuthVarianceField))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        InfoPanelLayout.setVerticalGroup(
            InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TrainSpeedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(TrainLocationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(BlockSpeedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(BlockAuthorityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(SpeedVarianceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(AuthVarianceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ControlPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Control Mode", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 255))); // NOI18N

        MovingBlockDisplay.setEditable(false);
        MovingBlockDisplay.setBackground(new java.awt.Color(255, 0, 0));
        MovingBlockDisplay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MovingBlockDisplay.setText("Moving Block");

        FixedBlockDisplay.setBackground(new java.awt.Color(0, 255, 0));
        FixedBlockDisplay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        FixedBlockDisplay.setText("Fixed Block");

        javax.swing.GroupLayout ControlPanelLayout = new javax.swing.GroupLayout(ControlPanel);
        ControlPanel.setLayout(ControlPanelLayout);
        ControlPanelLayout.setHorizontalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MovingBlockDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FixedBlockDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addContainerGap())
        );
        ControlPanelLayout.setVerticalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MovingBlockDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FixedBlockDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Train Scheduler", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 255))); // NOI18N

        sLabel9.setForeground(new java.awt.Color(240, 240, 240));
        sLabel9.setText("Glenbury:");

        sLabel10.setForeground(new java.awt.Color(240, 240, 240));
        sLabel10.setText("Dormont:");

        sLabel11.setForeground(new java.awt.Color(240, 240, 240));
        sLabel11.setText("Lebanon:");

        sLabel12.setForeground(new java.awt.Color(240, 240, 240));
        sLabel12.setText("Poplar:");

        sLabel13.setForeground(new java.awt.Color(240, 240, 240));
        sLabel13.setText("Shannon:");

        sLabel14.setForeground(new java.awt.Color(240, 240, 240));
        sLabel14.setText("Dormont:");

        sLabel15.setForeground(new java.awt.Color(240, 240, 240));
        sLabel15.setText("Glenbury:");

        sLabel16.setForeground(new java.awt.Color(240, 240, 240));
        sLabel16.setText("Overbrook:");

        sBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sBox2ActionPerformed(evt);
            }
        });

        sBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sBox6ActionPerformed(evt);
            }
        });

        sLabel17.setForeground(new java.awt.Color(240, 240, 240));
        sLabel17.setText("Inglewood:");

        NewScheduleButton.setText("Make New Schedule");
        NewScheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewScheduleButtonActionPerformed(evt);
            }
        });

        ViewScheduleButton.setText("View Schedule");
        ViewScheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewScheduleButtonActionPerformed(evt);
            }
        });

        AddScheduleButton.setText("Add To Schedule");
        AddScheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddScheduleButtonActionPerformed(evt);
            }
        });

        StartButton.setText("Start");

        LineSelectBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Red", "Green" }));
        LineSelectBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LineSelectBoxActionPerformed(evt);
            }
        });

        jLabel16.setText("Line:");

        sLabel8.setText("South:");

        sLabel7.setText("Station:");

        sLabel6.setText("First:");

        sLabel5.setText("Steel:");

        sLabel4.setText("Penn:");

        sLabel3.setText("Swiss:");

        sLabel2.setText("Herron:");

        sLabel1.setText("Shady:");

        sLabel18.setForeground(new java.awt.Color(240, 240, 240));
        sLabel18.setText("Central:");

        jLabel18.setText("Start Time:");

        StartTimeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartTimeBoxActionPerformed(evt);
            }
        });

        sBox9.setEditable(false);

        sBox10.setEditable(false);

        sBox11.setEditable(false);
        sBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sBox11ActionPerformed(evt);
            }
        });

        sBox12.setEditable(false);

        sBox13.setEditable(false);

        sBox14.setEditable(false);

        sBox15.setEditable(false);
        sBox15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sBox15ActionPerformed(evt);
            }
        });

        sBox16.setEditable(false);

        sBox17.setEditable(false);

        sBox18.setEditable(false);
        sBox18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sBox18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sLabel2)
                            .addComponent(sLabel3)
                            .addComponent(sLabel4)
                            .addComponent(sLabel5)
                            .addComponent(sLabel6)
                            .addComponent(sLabel7)
                            .addComponent(sLabel8)
                            .addComponent(sLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(sBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(sLabel11))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(sBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(sLabel10))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(sBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(sLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(sBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(sLabel15))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(sBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(sLabel14))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(sBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(sLabel13))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(sBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(sLabel9))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(sBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sLabel17)
                                            .addComponent(sLabel16)
                                            .addComponent(sLabel18))))
                                .addGap(0, 32, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sBox9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sBox10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sBox11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sBox12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sBox13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sBox14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sBox15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sBox16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(sBox17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(StartTimeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LineSelectBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sBox18, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(AddScheduleButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NewScheduleButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ViewScheduleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(StartButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LineSelectBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sLabel1)
                            .addComponent(sLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sLabel2)
                            .addComponent(sLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sLabel4))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sLabel8)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(sBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sBox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sBox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sBox13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sBox14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sBox15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sBox16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sBox17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sLabel17))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sBox18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartTimeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewScheduleButton)
                    .addComponent(ViewScheduleButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddScheduleButton)
                    .addComponent(StartButton)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Block Control Mode", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 255))); // NOI18N

        ControlMode.add(MovingBlockRadio);
        MovingBlockRadio.setText("Moving Block");
        MovingBlockRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovingBlockRadioActionPerformed(evt);
            }
        });

        ControlMode.add(FixedBlockRadio);
        FixedBlockRadio.setSelected(true);
        FixedBlockRadio.setText("Fixed Block");
        FixedBlockRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FixedBlockRadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MovingBlockRadio)
                    .addComponent(FixedBlockRadio))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MovingBlockRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FixedBlockRadio)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TrainList, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(PassengerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ControlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TrainList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PassengerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(InfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ControlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TrainSpeedFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrainSpeedFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TrainSpeedFieldActionPerformed

    private void SpeedVarianceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpeedVarianceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SpeedVarianceFieldActionPerformed

    private void TrainListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrainListActionPerformed
        /*String new_label = (String)TrainList.getSelectedItem();
        TrainList.setSelectedItem(new_label);
        
        int index = Integer.parseInt(new_label)-1;
        MBOTrain train_to_show = trains.get(index);
        //curr_train = train_to_show;
        
        updateDisplay();*/
    }//GEN-LAST:event_TrainListActionPerformed

    private void MovingBlockRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovingBlockRadioActionPerformed
        MovingBlockDisplay.setBackground(Color.GREEN);
        FixedBlockDisplay.setBackground(Color.RED);
        mode = 1;
        updateDisplay();
    }//GEN-LAST:event_MovingBlockRadioActionPerformed

    private void FixedBlockRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FixedBlockRadioActionPerformed
        FixedBlockDisplay.setBackground(Color.GREEN);
        MovingBlockDisplay.setBackground(Color.RED);
        mode = 0;
        updateDisplay();
    }//GEN-LAST:event_FixedBlockRadioActionPerformed

    private void BlockSpeedFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlockSpeedFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BlockSpeedFieldActionPerformed

    private void AddScheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddScheduleButtonActionPerformed
        String line = (String)LineSelectBox.getSelectedItem();
        if(line.equals("Red")){
            double start_time = Double.parseDouble(StartTimeBox.getText());
            double d_time = Double.parseDouble(sBox1.getText());
            double time_to_add = start_time + d_time;
            ScheduleNode node_to_add = schedule.get(0);
            node_to_add.addTime(time_to_add);
            d_time = Double.parseDouble(sBox2.getText());
            time_to_add += d_time;
            node_to_add = schedule.get(1);
            node_to_add.addTime(time_to_add);
            d_time = Double.parseDouble(sBox3.getText());
            time_to_add += d_time;
            node_to_add = schedule.get(2);
            node_to_add.addTime(time_to_add);
            d_time = Double.parseDouble(sBox4.getText());
            time_to_add += d_time;
            node_to_add = schedule.get(3);
            node_to_add.addTime(time_to_add);
            d_time = Double.parseDouble(sBox5.getText());
            time_to_add += d_time;
            node_to_add = schedule.get(4);
            node_to_add.addTime(time_to_add);
            d_time = Double.parseDouble(sBox6.getText());
            time_to_add += d_time;
            node_to_add = schedule.get(5);
            node_to_add.addTime(time_to_add);
            d_time = Double.parseDouble(sBox7.getText());
            time_to_add += d_time;
            node_to_add = schedule.get(6);
            node_to_add.addTime(time_to_add);
            d_time = Double.parseDouble(sBox8.getText());
            time_to_add += d_time;
            node_to_add = schedule.get(7);
            node_to_add.addTime(time_to_add);
        }
        else{
            double start_time = Double.parseDouble(StartTimeBox.getText());
            double d_time = Double.parseDouble(sBox1.getText());
            double time_to_add = start_time + d_time;
            ScheduleNode node_to_add = schedule.get(0);
            node_to_add.addTime(time_to_add);
            d_time = Double.parseDouble(sBox2.getText());
            time_to_add += d_time;
            node_to_add = schedule.get(1);
            node_to_add.addTime(time_to_add);
            d_time = Double.parseDouble(sBox3.getText());
            time_to_add += d_time;
            node_to_add = schedule.get(2);
            node_to_add.addTime(time_to_add);
            d_time = Double.parseDouble(sBox4.getText());
            time_to_add += d_time;
            node_to_add = schedule.get(3);
            node_to_add.addTime(time_to_add);
            d_time = Double.parseDouble(sBox5.getText());
            time_to_add += d_time;
            node_to_add = schedule.get(4);
            node_to_add.addTime(time_to_add);
            d_time = Double.parseDouble(sBox6.getText());
            time_to_add += d_time;
            node_to_add = schedule.get(5);
            node_to_add.addTime(time_to_add);
            d_time = Double.parseDouble(sBox7.getText());
            time_to_add += d_time;
            node_to_add = schedule.get(6);
            node_to_add.addTime(time_to_add);
            d_time = Double.parseDouble(sBox8.getText());
            time_to_add += d_time;
            node_to_add = schedule.get(7);
            node_to_add.addTime(time_to_add);
            d_time = Double.parseDouble(sBox9.getText());
            time_to_add += + d_time;
            node_to_add = schedule.get(8);
            node_to_add.addTime(time_to_add);
            d_time = Double.parseDouble(sBox10.getText());
            time_to_add += d_time;
            node_to_add = schedule.get(9);
            node_to_add.addTime(time_to_add);
            d_time = Double.parseDouble(sBox11.getText());
            time_to_add += d_time;
            node_to_add = schedule.get(10);
            node_to_add.addTime(time_to_add);
            d_time = Double.parseDouble(sBox12.getText());
            time_to_add += d_time;
            node_to_add = schedule.get(11);
            node_to_add.addTime(time_to_add);
            d_time = Double.parseDouble(sBox13.getText());
            time_to_add += d_time;
            node_to_add = schedule.get(12);
            node_to_add.addTime(time_to_add);
            d_time = Double.parseDouble(sBox14.getText());
            time_to_add += d_time;
            node_to_add = schedule.get(13);
            node_to_add.addTime(time_to_add);
            d_time = Double.parseDouble(sBox15.getText());
            time_to_add += d_time;
            node_to_add = schedule.get(14);
            node_to_add.addTime(time_to_add);
            d_time = Double.parseDouble(sBox16.getText());
            time_to_add += d_time;
            node_to_add = schedule.get(15);
            node_to_add.addTime(time_to_add);
            d_time = Double.parseDouble(sBox17.getText());
            time_to_add += d_time;
            node_to_add = schedule.get(16);
            node_to_add.addTime(time_to_add);
            d_time = Double.parseDouble(sBox18.getText());
            time_to_add += d_time;
            node_to_add = schedule.get(17);
            node_to_add.addTime(time_to_add);
        }
    }//GEN-LAST:event_AddScheduleButtonActionPerformed

    private void ViewScheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewScheduleButtonActionPerformed
        System.out.println(schedule);
    }//GEN-LAST:event_ViewScheduleButtonActionPerformed

    private void NewScheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewScheduleButtonActionPerformed
        String line = (String)LineSelectBox.getSelectedItem();
        if(line.equals("Red")){
            schedule = new ArrayList();
            double start_time = Double.parseDouble(StartTimeBox.getText());
            double d_time = Double.parseDouble(sBox1.getText());
            double time_to_add = start_time + d_time;
            ScheduleNode node_to_add = new ScheduleNode(sLabel1.getText(),time_to_add);
            schedule.add(node_to_add);
            d_time = Double.parseDouble(sBox2.getText());
            time_to_add += d_time;
            node_to_add = new ScheduleNode(sLabel2.getText(),time_to_add);
            schedule.add(node_to_add);
            d_time = Double.parseDouble(sBox3.getText());
            time_to_add += d_time;
            node_to_add = new ScheduleNode(sLabel3.getText(),time_to_add);
            schedule.add(node_to_add);
            d_time = Double.parseDouble(sBox4.getText());
            time_to_add += d_time;
            node_to_add = new ScheduleNode(sLabel4.getText(),time_to_add);
            schedule.add(node_to_add);
            d_time = Double.parseDouble(sBox5.getText());
            time_to_add += d_time;
            node_to_add = new ScheduleNode(sLabel5.getText(),time_to_add);
            schedule.add(node_to_add);
            d_time = Double.parseDouble(sBox6.getText());
            time_to_add += d_time;
            node_to_add = new ScheduleNode(sLabel6.getText(),time_to_add);
            schedule.add(node_to_add);
            d_time = Double.parseDouble(sBox7.getText());
            time_to_add += d_time;
            node_to_add = new ScheduleNode(sLabel7.getText(),time_to_add);
            schedule.add(node_to_add);
            d_time = Double.parseDouble(sBox8.getText());
            time_to_add += d_time;
            node_to_add = new ScheduleNode(sLabel8.getText(),time_to_add);
            schedule.add(node_to_add);
        }
        else{
            schedule = new ArrayList();
            double start_time = Double.parseDouble(StartTimeBox.getText());
            double d_time = Double.parseDouble(sBox1.getText());
            double time_to_add = start_time + d_time;
            ScheduleNode node_to_add = new ScheduleNode(sLabel1.getText(),time_to_add);
            schedule.add(node_to_add);
            d_time = Double.parseDouble(sBox2.getText());
            time_to_add += d_time;
            node_to_add = new ScheduleNode(sLabel2.getText(),time_to_add);
            schedule.add(node_to_add);
            d_time = Double.parseDouble(sBox3.getText());
            time_to_add += d_time;
            node_to_add = new ScheduleNode(sLabel3.getText(),time_to_add);
            schedule.add(node_to_add);
            d_time = Double.parseDouble(sBox4.getText());
            time_to_add += d_time;
            node_to_add = new ScheduleNode(sLabel4.getText(),time_to_add);
            schedule.add(node_to_add);
            d_time = Double.parseDouble(sBox5.getText());
            time_to_add += d_time;
            node_to_add = new ScheduleNode(sLabel5.getText(),time_to_add);
            schedule.add(node_to_add);
            d_time = Double.parseDouble(sBox6.getText());
            time_to_add += d_time;
            node_to_add = new ScheduleNode(sLabel6.getText(),time_to_add);
            schedule.add(node_to_add);
            d_time = Double.parseDouble(sBox7.getText());
            time_to_add += d_time;
            node_to_add = new ScheduleNode(sLabel7.getText(),time_to_add);
            schedule.add(node_to_add);
            d_time = Double.parseDouble(sBox8.getText());
            time_to_add += d_time;
            node_to_add = new ScheduleNode(sLabel8.getText(),time_to_add);
            schedule.add(node_to_add);
            d_time = Double.parseDouble(sBox9.getText());
            time_to_add += d_time;
            node_to_add = new ScheduleNode(sLabel9.getText(),time_to_add);
            schedule.add(node_to_add);
            d_time = Double.parseDouble(sBox10.getText());
            time_to_add += d_time;
            node_to_add = new ScheduleNode(sLabel10.getText(),time_to_add);
            schedule.add(node_to_add);
            d_time = Double.parseDouble(sBox11.getText());
            time_to_add += d_time;
            node_to_add = new ScheduleNode(sLabel11.getText(),time_to_add);
            schedule.add(node_to_add);
            d_time = Double.parseDouble(sBox12.getText());
            time_to_add += d_time;
            node_to_add = new ScheduleNode(sLabel12.getText(),time_to_add);
            schedule.add(node_to_add);
            d_time = Double.parseDouble(sBox13.getText());
            time_to_add += d_time;
            node_to_add = new ScheduleNode(sLabel13.getText(),time_to_add);
            schedule.add(node_to_add);
            d_time = Double.parseDouble(sBox14.getText());
            time_to_add += d_time;
            node_to_add = new ScheduleNode(sLabel14.getText(),time_to_add);
            schedule.add(node_to_add);
            d_time = Double.parseDouble(sBox15.getText());
            time_to_add += d_time;
            node_to_add = new ScheduleNode(sLabel15.getText(),time_to_add);
            schedule.add(node_to_add);
            d_time = Double.parseDouble(sBox16.getText());
            time_to_add += d_time;
            node_to_add = new ScheduleNode(sLabel16.getText(),time_to_add);
            schedule.add(node_to_add);
            d_time = Double.parseDouble(sBox17.getText());
            time_to_add += d_time;
            node_to_add = new ScheduleNode(sLabel17.getText(),time_to_add);
            schedule.add(node_to_add);
            d_time = Double.parseDouble(sBox18.getText());
            time_to_add += d_time;
            node_to_add = new ScheduleNode(sLabel18.getText(),time_to_add);
            schedule.add(node_to_add);
        }
        LineSelectBox.setEnabled(false);
    }//GEN-LAST:event_NewScheduleButtonActionPerformed

    private void sBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sBox6ActionPerformed

    private void sBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sBox2ActionPerformed

    private void StartTimeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartTimeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StartTimeBoxActionPerformed

    private void sBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sBox11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sBox11ActionPerformed

    private void sBox15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sBox15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sBox15ActionPerformed

    private void sBox18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sBox18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sBox18ActionPerformed

    private void LineSelectBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LineSelectBoxActionPerformed
        String new_label = (String)LineSelectBox.getSelectedItem();
        TrainList.setSelectedItem(new_label);
        
        if(new_label.equals("Red")){
           sLabel1.setText("Shady");
           sLabel2.setText("Herron");
           sLabel3.setText("Swiss");
           sLabel4.setText("Penn");
           sLabel5.setText("Steel");
           sLabel6.setText("First");
           sLabel7.setText("Station");
           sLabel8.setText("South");
           sLabel9.setForeground(new Color(240,240,240));
           sLabel10.setForeground(new Color(240,240,240));
           sLabel11.setForeground(new Color(240,240,240));
           sLabel12.setForeground(new Color(240,240,240));
           sLabel13.setForeground(new Color(240,240,240));
           sLabel14.setForeground(new Color(240,240,240));
           sLabel15.setForeground(new Color(240,240,240));
           sLabel16.setForeground(new Color(240,240,240));
           sLabel17.setForeground(new Color(240,240,240));
           sLabel18.setForeground(new Color(240,240,240));
           sBox9.setText(null);
           sBox10.setText(null);
           sBox11.setText(null);
           sBox12.setText(null);
           sBox13.setText(null);
           sBox14.setText(null);
           sBox15.setText(null);
           sBox16.setText(null);
           sBox17.setText(null);
           sBox18.setText(null);
           sBox9.setEditable(false);
           sBox10.setEditable(false);
           sBox11.setEditable(false);
           sBox12.setEditable(false);
           sBox13.setEditable(false);
           sBox14.setEditable(false);
           sBox15.setEditable(false);
           sBox16.setEditable(false);
           sBox17.setEditable(false);
           sBox18.setEditable(false);
        }
        else{
           sLabel1.setText("Pioneer");
           sLabel2.setText("Edgebrook");
           sLabel3.setText("Station");
           sLabel4.setText("Whited");
           sLabel5.setText("Southbank");
           sLabel6.setText("Central");
           sLabel7.setText("Inglewood");
           sLabel8.setText("Overbrook");
           sLabel9.setForeground(new Color(0,0,0));
           sLabel10.setForeground(new Color(0,0,0));
           sLabel11.setForeground(new Color(0,0,0));
           sLabel12.setForeground(new Color(0,0,0));
           sLabel13.setForeground(new Color(0,0,0));
           sLabel14.setForeground(new Color(0,0,0));
           sLabel15.setForeground(new Color(0,0,0));
           sLabel16.setForeground(new Color(0,0,0));
           sLabel17.setForeground(new Color(0,0,0));
           sLabel18.setForeground(new Color(0,0,0));
           sBox9.setEditable(true);
           sBox10.setEditable(true);
           sBox11.setEditable(true);
           sBox12.setEditable(true);
           sBox13.setEditable(true);
           sBox14.setEditable(true);
           sBox15.setEditable(true);
           sBox16.setEditable(true);
           sBox17.setEditable(true);
           sBox18.setEditable(true);
        }
    }//GEN-LAST:event_LineSelectBoxActionPerformed

    private void TotalTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovingBlockOverlayUI().setVisible(true);
            }
        });
    }
    
    public void updateDisplay(){
        //Get current train info
        int curr_train_num = Integer.parseInt((String)TrainList.getSelectedItem()) - 1;
        curr_train = trains.get(curr_train_num);
        speed = curr_train.getCurrentSpeed();
        double speed_in_mph = speed * 2.23694;
        location = curr_train.getCurrentPosition();
        double location_in_feet = location * 3.28084;
        //Set Train info panel
        TrainSpeedField.setText(String.format("%5f",speed_in_mph) + " mph");
        TrainLocationField.setText(String.format("%5f",location_in_feet) + " ft");
        BlockSpeedField.setText(String.format("%5f",bspeed * 2.23694) + " mph");
        BlockAuthorityField.setText(String.format("%f",bauth * 3.28084) + " ft");
        //Calculate and display block info
        double speed_var = bspeed - speed;
        SpeedVarianceField.setText(String.format("%5f",speed_var));
        double auth_var = bauth - location;
        AuthVarianceField.setText(String.format("%5f",auth_var));
    }
    
    public void addTrain(int ID){
        TrainList.addItem(String.valueOf(ID));
    }
    
    public void updateTrainList(Vector<TrainModel> TL){
        trains = TL;
    }

    
    public double calculateSafeAuthority(TrainModel curr_train){
        double loc1 = curr_train.getCurrentPosition();
        double speed1 = curr_train.getCurrentSpeed();
        double loc2 = Double.MAX_VALUE;
        double speed2 = 0;
        for(TrainModel t : trains){
            if(t.getCurrentPosition() < loc2){
                loc2 = t.getCurrentPosition();
                speed2 = t.getCurrentSpeed();
            }
        }
        double v_final = 0;
        double t_final = (0 - speed1)/deceleration;
        double distance = speed1 * t_final + .5 * deceleration * Math.pow(t_final, 2);
        return loc2 - (distance + loc1);
    }
    
    public double calculateSafeSpeed(TrainModel curr_train){
        double loc1 = curr_train.getCurrentPosition();
        double speed1 = curr_train.getCurrentSpeed();
        double loc2 = Double.MAX_VALUE;
        double speed2 = 0;
        for(TrainModel t : trains){
            if(t.getCurrentPosition() < loc2){
                loc2 = t.getCurrentPosition();
                speed2 = t.getCurrentSpeed();
            }
        }
        return speed2;
    }

    public ArrayList getSchedule(){
        return schedule;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton AddScheduleButton;
    public javax.swing.JTextField AuthVarianceField;
    public javax.swing.JTextField BlockAuthorityField;
    public javax.swing.JTextField BlockSpeedField;
    private javax.swing.ButtonGroup ControlMode;
    public javax.swing.JPanel ControlPanel;
    public javax.swing.JTextField FixedBlockDisplay;
    public javax.swing.JRadioButton FixedBlockRadio;
    public javax.swing.JPanel InfoPanel;
    private javax.swing.JComboBox LineSelectBox;
    public javax.swing.JTextField MovingBlockDisplay;
    public javax.swing.JRadioButton MovingBlockRadio;
    public javax.swing.JButton NewScheduleButton;
    public javax.swing.JPanel PassengerPanel;
    public javax.swing.JTextField SpeedVarianceField;
    public javax.swing.JButton StartButton;
    private javax.swing.JTextField StartTimeBox;
    public javax.swing.JTextField TotalText;
    public javax.swing.JComboBox TrainList;
    public javax.swing.JTextField TrainLocationField;
    public javax.swing.JTextField TrainSpeedField;
    public javax.swing.JButton ViewScheduleButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFrame jFrame1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel24;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JTextField sBox1;
    private javax.swing.JTextField sBox10;
    private javax.swing.JTextField sBox11;
    private javax.swing.JTextField sBox12;
    private javax.swing.JTextField sBox13;
    private javax.swing.JTextField sBox14;
    private javax.swing.JTextField sBox15;
    private javax.swing.JTextField sBox16;
    private javax.swing.JTextField sBox17;
    private javax.swing.JTextField sBox18;
    public javax.swing.JTextField sBox2;
    public javax.swing.JTextField sBox3;
    public javax.swing.JTextField sBox4;
    public javax.swing.JTextField sBox5;
    public javax.swing.JTextField sBox6;
    public javax.swing.JTextField sBox7;
    public javax.swing.JTextField sBox8;
    public javax.swing.JTextField sBox9;
    private javax.swing.JLabel sLabel1;
    public javax.swing.JLabel sLabel10;
    public javax.swing.JLabel sLabel11;
    public javax.swing.JLabel sLabel12;
    public javax.swing.JLabel sLabel13;
    public javax.swing.JLabel sLabel14;
    public javax.swing.JLabel sLabel15;
    public javax.swing.JLabel sLabel16;
    public javax.swing.JLabel sLabel17;
    private javax.swing.JLabel sLabel18;
    private javax.swing.JLabel sLabel2;
    private javax.swing.JLabel sLabel3;
    private javax.swing.JLabel sLabel4;
    private javax.swing.JLabel sLabel5;
    private javax.swing.JLabel sLabel6;
    private javax.swing.JLabel sLabel7;
    private javax.swing.JLabel sLabel8;
    public javax.swing.JLabel sLabel9;
    // End of variables declaration//GEN-END:variables
}
